---
- name: Update block
  tags: ['never', 'create', 'update']
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: yes
        autoremove: yes

    - name: Reboot server
      ansible.builtin.reboot:

    - name: Wait for SSH connection
      wait_for_connection:
        timeout: 300

- name: Install software
  tags: ['never', 'create','update']
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop: "{{ install_software }}"

- name: Log out of server on idle
  tags: ['never', 'create','update']
  block:
    - name: Update /etc/profile
      ansible.builtin.lineinfile:
        path: /etc/profile
        line: export TMOUT={{ bash_profile_logout_seconds }}
        state: present
